### ISSUE TITLE
How to test the backend flask api with Curl command

### ISSUE THREAD

**Issue by mkscala** [keathmilligan/flask-ng2-jwt-example#1]
Gettting the below error

**$ curl -i http://localhost:5000/unprotected**
HTTP/1.0 200 OK
Content-Type: application/json
Access-Control-Allow-Origin: *
Content-Length: 52
Server: Werkzeug/0.11.11 Python/2.7.6
Date: Wed, 12 Oct 2016 23:23:09 GMT

{
  "message": "This is an unprotected resource."
}

**$ curl -i http://localhost:5000/protected**
HTTP/1.0 401 UNAUTHORIZED
Content-Type: application/json
WWW-Authenticate: JWT realm="Login Required"
Access-Control-Allow-Origin: *
Content-Length: 125
Server: Werkzeug/0.11.11 Python/2.7.6
Date: Wed, 12 Oct 2016 23:23:18 GMT

{
  _"description": "Request does not contain an access token",
  "error": "Authorization Required",
  "status_code": 401_
}

**Comment by keathmilligan** [comment]
This is the return you would expect when you do not supply a token. In order to get the protected resource, you need to post to the /auth server first with the username and password to get the access token. See https://pythonhosted.org/Flask-JWT/.

**Comment by mkscala** [comment]
in the Flask backend where is the CORS enabled. I just see you send the CORS headers in the after_request decorator. just passing in the Header Flask/Angular 2 will take care of CORS ?
Did we use  pip install -U flask-cors ?
 below https://flask-cors.readthedocs.io/en/latest/

**Comment by keathmilligan** [comment]
This example is extremely minimal - just sending the CORS headers in the after decorator is sufficient for this case. Flask-cors would give you much more control, but I'm not using it here.
